InventoryManager
ITEM_TYPE
vector<string> InventoryManager::potion_inventory
Referenced by InsertIntoInventoryManager, Player::PlayerCollisions, RemoveFromInventoryManager.
char InventoryManager::c_health
Referenced by Player::PlayerCollisions.
char InventoryManager::c_shield
Referenced by Player::PlayerCollisions.
char InventoryManager::c_health_potion
Referenced by DropItemSelected, InsertIntoInventoryManager, Player::PlayerCollisions, RemoveFromInventoryManager, UsePotionSelected.
char InventoryManager::c_shield_potion
Referenced by DropItemSelected, InsertIntoInventoryManager, Player::PlayerCollisions, RemoveFromInventoryManager, UsePotionSelected.
char InventoryManager::c_magic_potion
Referenced by DropItemSelected, InsertIntoInventoryManager, Player::PlayerCollisions, RemoveFromInventoryManager, UsePotionSelected.
unsigned int InventoryManager::inventory_index
Referenced by CurrentInventoryIndex, DropItemSelected, InventoryControl, Player::PlayerInput, UsePotionSelected.
bool InventoryManager::inventory_open
Referenced by InventoryControl, InventoryInput, Player::PlayerInput, ConsoleRendering::Render_GUI, ConsoleRendering::Render_Inventory, Player::RenderPlayer.
string InventoryManager::utilities[3][2][3][2]
string InventoryManager::weaponsAndArmour[3][2][3][2]
string InventoryManager::trinkets[2][2][2][2]
char InventoryManager::potion_chars[3][3]
Referenced by WhatIsItem.
char InventoryManager::weapon_chars[3][3]
Referenced by WhatIsItem.
bool InventoryManager::highlight
bool InventoryManager::on_title_screen
vector<string> InventoryManager::weapon_inventory
vector<string> InventoryManager::armour_inventory
vector<string> InventoryManager::trinket_inventory
vector<string> InventoryManager::utility_inventory
string InventoryManager::item_picked_up
bool InventoryManager::InsertIntoInventoryManager(ITEM_TYPE item, char nextMove, Player &p, UserInterfaceManager &ui)
References AddSpaceAndEnding, BLANK, c_health_potion, c_magic_potion, c_shield_potion, Player::health_potions, UserInterfaceManager::inventory, Player::magic_potions, POTION, potion_inventory, Player::shield_potions, WEAPON.
Referenced by Player::PlayerCollisions.
void InventoryManager::RemoveFromInventoryManager(ITEM_TYPE item, char nextMove, Player &p, UserInterfaceManager &ui)
References AddSpaceAndEnding, BLANK, c_health_potion, c_magic_potion, c_shield_potion, Player::health_potions, UserInterfaceManager::inventory, POTION, potion_inventory, Player::shield_potions, WEAPON.
Referenced by DropItemSelected, UsePotionSelected.
void InventoryManager::InventoryStart()
void InventoryManager::InventoryControl(char action, ConsoleRendering &r, InventoryManager &i, ConsoleWindowManager &c, MapManager &m, UserInterfaceManager &ui)
References inventory_index, inventory_open, ConsoleRendering::Render_Inventory.
Referenced by Player::PlayerInput.
void InventoryManager::UsePotionSelected(int potion, Player &p, ConsoleWindowManager &c, MapManager &m, InventoryManager &i, ConsoleRendering &r, UserInterfaceManager &ui)
References ConsoleWindowManager::BlankScreen, c_health_potion, c_magic_potion, c_shield_potion, Player::health, Player::health_potions, inventory_index, Player::magic, Player::magic_potions, Player::max_stats, POTION, RemoveFromInventoryManager, ConsoleRendering::Render_Inventory, Player::shield, Player::shield_potions, UpdateInventory.
Referenced by Player::PlayerInput.
void InventoryManager::DropItemSelected(int type, Player &p, ConsoleWindowManager &c, MapManager &m, InventoryManager &i, ConsoleRendering &r, UserInterfaceManager &ui)
References ConsoleWindowManager::BlankScreen, c_health_potion, c_magic_potion, c_shield_potion, Player::health_potions, inventory_index, MapManager::IsEmpty, Player::magic_potions, MapManager::new_map, Player::player_position_x, Player::player_position_y, POTION, RemoveFromInventoryManager, ConsoleRendering::Render_Inventory, Player::shield_potions, UpdateInventory, MapManager::width.
Referenced by Player::PlayerInput.
void InventoryManager::InventoryInput(ConsoleWindowManager &c, MapManager &m, InventoryManager &i, ConsoleRendering &r, UserInterfaceManager &ui)
References inventory_open, ConsoleRendering::Render_Inventory.
Referenced by main.
void InventoryManager::UpdateInventory(InventoryManager &i, UserInterfaceManager &ui)
References AddSpaceAndEnding, CurrentInventoryIndex, UserInterfaceManager::inventory.
Referenced by DropItemSelected, main, UsePotionSelected.
int InventoryManager::GetInventoryHeadingLocation(string s, UserInterfaceManager &ui)
References UserInterfaceManager::inventory.
Referenced by Player::PlayerCollisions.
string InventoryManager::CurrentInventoryIndex(InventoryManager &i)
References inventory_index.
Referenced by main, UpdateInventory.
string InventoryManager::AddSpaceAndEnding(string input, UserInterfaceManager &ui)
References UserInterfaceManager::inventory.
Referenced by InsertIntoInventoryManager, RemoveFromInventoryManager, UpdateInventory.
InventoryManager::ITEM_TYPE InventoryManager::WhatIsItem(char letter)
References BLANK, POTION, potion_chars, WEAPON, weapon_chars.
Referenced by Player::PlayerCollisions.