Player
int Player::player_position_x
Referenced by InventoryManager::DropItemSelected, PlayerCollisions, PlayerCollisionsChecks, PlayerInput, RenderPlayer.
int Player::player_position_y
Referenced by InventoryManager::DropItemSelected, PlayerCollisions, PlayerCollisionsChecks, PlayerInput, RenderPlayer.
int Player::player_position_x_new
Referenced by BlankPosition, MapManager::FindEnemy, MapManager::FindFriendly, MapManager::LoadNextMap, PlayerCollisions, PlayerCollisionsChecks, PlayerInput, RenderPlayer.
int Player::player_position_y_new
Referenced by BlankPosition, MapManager::FindEnemy, MapManager::FindFriendly, MapManager::LoadNextMap, PlayerCollisions, PlayerCollisionsChecks, PlayerInput, RenderPlayer.
bool Player::end_game
bool Player::in_combat
Referenced by CombatManager::Fight, MapManager::LoadNextMap, PlayerInput, ConsoleRendering::Render_All.
int Player::damage
Referenced by GetDamage.
int Player::shield
Referenced by Debug::DebugControls, EnterMessageMode, PlayerCollisions, ConsoleRendering::Print_Stats, InventoryManager::UsePotionSelected.
int Player::health
Referenced by Debug::DebugControls, EnterMessageMode, GetHealth, PlayerCollisions, ConsoleRendering::Print_Stats, SetDesiredHealth, InventoryManager::UsePotionSelected.
int Player::magic
Referenced by Debug::DebugControls, EnterMessageMode, ConsoleRendering::Print_Stats, InventoryManager::UsePotionSelected.
int Player::max_stats
Referenced by PlayerCollisions, InventoryManager::UsePotionSelected.
int Player::health_potions
Referenced by InventoryManager::DropItemSelected, InventoryManager::InsertIntoInventoryManager, PlayerCollisions, InventoryManager::RemoveFromInventoryManager, InventoryManager::UsePotionSelected.
int Player::shield_potions
Referenced by InventoryManager::DropItemSelected, InventoryManager::InsertIntoInventoryManager, PlayerCollisions, InventoryManager::RemoveFromInventoryManager, InventoryManager::UsePotionSelected.
int Player::magic_potions
Referenced by InventoryManager::DropItemSelected, InventoryManager::InsertIntoInventoryManager, PlayerCollisions, InventoryManager::UsePotionSelected.
int Player::max_potions
Referenced by PlayerCollisions.
const char Player::c_player
Referenced by RenderPlayer.
bool Player::waiting_to_start_combat
Referenced by EnterCombatMode, PlayerInput.
bool Player::waiting_for_choice
Referenced by EnterMessageMode.
int Player::GetDamage()
References damage.
Referenced by CombatManager::HitEnemy, CombatManager::PrintStatements.
int Player::GetHealth()
References health.
Referenced by CombatManager::HitPlayer, CombatManager::PrintStatements, CombatManager::UpdateResults.
void Player::SetDesiredHealth(int value)
References health.
Referenced by CombatManager::HitPlayer.
void Player::RenderPlayer(MapManager &m, ConsoleWindowManager &c, InventoryManager &i)
References ConsoleWindowManager::BLACK, c_player, Macro::GoToScreenPosition, InventoryManager::inventory_open, ConsoleWindowManager::LIGHT_BLUE, ConsoleWindowManager::MAGENTA, MapManager::new_map, player_position_x, player_position_x_new, player_position_y, player_position_y_new, ConsoleWindowManager::SetConsoleWindowColor, MapManager::width.
Referenced by MapManager::LoadNextMap, main.
void Player::PlayerCollisions(MapManager &m, ConsoleWindowManager &c, Player &p, InventoryManager &i, UserInterfaceManager &ui)
References BlankPosition, InventoryManager::c_health, InventoryManager::c_health_potion, InventoryManager::c_magic_potion, InventoryManager::c_shield, InventoryManager::c_shield_potion, MapManager::enemies, EnterCombatMode, EnterMessageMode, MapManager::file_contents_read_in, MapManager::FindEnemy, MapManager::FindFriendly, MapManager::generic_friendlies, InventoryManager::GetInventoryHeadingLocation, health, health_potions, InventoryManager::InsertIntoInventoryManager, UserInterfaceManager::inventory, MapManager::LoadNextMap, magic_potions, max_potions, max_stats, MapManager::new_map, player_position_x, player_position_x_new, player_position_y, player_position_y_new, PlayerCollisionsChecks, InventoryManager::POTION, InventoryManager::potion_inventory, shield, shield_potions, InventoryManager::WEAPON, InventoryManager::WhatIsItem, MapManager::width.
Referenced by main.
void Player::PlayerInput(InventoryManager &i, ConsoleWindowManager &c, MapManager &m, Player &p, ConsoleRendering &r, UserInterfaceManager &ui, CombatManager &cm)
References InventoryManager::DropItemSelected, MapManager::enemies, CombatManager::Fight, MapManager::FindEnemy, in_combat, InventoryManager::inventory_index, InventoryManager::inventory_open, InventoryManager::InventoryControl, player_position_x, player_position_x_new, player_position_y, player_position_y_new, InventoryManager::UsePotionSelected, waiting_to_start_combat.
Referenced by main.
int Player::PlayerCollisionsChecks(int item, int item_max, MapManager &m, Player &p)
References BlankPosition, player_position_x, player_position_x_new, player_position_y, player_position_y_new.
Referenced by PlayerCollisions.
bool Player::BlankPosition(MapManager &m, Player &p)
References MapManager::new_map, player_position_x_new, player_position_y_new, MapManager::width.
Referenced by PlayerCollisions, PlayerCollisionsChecks.
void Player::EnterCombatMode(MapManager &m, Enemy &e)
References Macro::GoToScreenPosition, MapManager::height, Enemy::PrintDetails, waiting_to_start_combat.
Referenced by PlayerCollisions.
void Player::EnterMessageMode(MapManager &m, GenericFriendly &f)
References Macro::GoToScreenPosition, health, MapManager::height, magic, GenericFriendly::PrintMessage, shield, waiting_for_choice.
Referenced by PlayerCollisions.