CombatManager
TURN
RESULTS
int CombatManager::sleep_timer
TURN CombatManager::_TURN
Referenced by Fight, SetTurn.
RESULTS CombatManager::_RESULTS
Referenced by Fight, UpdateResults.
void CombatManager::Fight(Player &p, MapManager &m, Enemy &e)
References _RESULTS, _TURN, ENEMY, ENEMY_DEAD, HitEnemy, HitPlayer, Player::in_combat, PLAYER, PLAYER_DEAD, PrintStatements, SetTurn, UpdateResults.
Referenced by Player::PlayerInput.
void CombatManager::SetTurn(TURN desired_turn)
References _TURN.
Referenced by Fight.
void CombatManager::HitEnemy(Enemy &e, Player &p)
References Player::GetDamage, NonPlayableCharacter::GetHealth, NonPlayableCharacter::SetDesiredHealth, SleepTimer.
Referenced by Fight.
void CombatManager::HitPlayer(Enemy &e, Player &p)
References NonPlayableCharacter::GetDamage, Player::GetHealth, Player::SetDesiredHealth, SleepTimer.
Referenced by Fight.
void CombatManager::PrintStatements(MapManager &m, Enemy &e, Player &p, int statements)
References NonPlayableCharacter::GetDamage, Player::GetDamage, NonPlayableCharacter::GetHealth, Player::GetHealth, NonPlayableCharacter::GetName, Macro::GoToScreenPosition, MapManager::height, SleepTimer.
Referenced by Fight.
void CombatManager::UpdateResults(Enemy &e, Player &p)
References _RESULTS, ENEMY_DEAD, NonPlayableCharacter::GetHealth, Player::GetHealth, PLAYER_DEAD.
Referenced by Fight.
void CombatManager::SleepTimer()
Referenced by HitEnemy, HitPlayer, PrintStatements.