Enemy
Enemy::Enemy(int x, int y)
References NonPlayableCharacter::SetHealth, NonPlayableCharacter::SetName, SetNamesArray, SetPassive, NonPlayableCharacter::SetPosition, NonPlayableCharacter::SetSpeed, NonPlayableCharacter::SetStrength.
void Enemy::PrintDetails(MapManager &m)
References NonPlayableCharacter::GetDamage, NonPlayableCharacter::GetHealth, NonPlayableCharacter::GetName, Macro::GoToScreenPosition, NonPlayableCharacter::health, MapManager::height, NonPlayableCharacter::name.
Referenced by Player::EnterCombatMode.
void Enemy::SetNamesArray() override
References NonPlayableCharacter::name_array.
Referenced by Enemy.
void Enemy::SetPassive() override
References NonPlayableCharacter::passive.
Referenced by Enemy.