GenericFriendly
string GenericFriendly::messages_array[20][20]
Referenced by SetMessages, SetRandomMessage.
string GenericFriendly::message
Referenced by GetMessage, PrintMessage, SetRandomMessage.
GenericFriendly::GenericFriendly(int postition)
References SetMessages, SetNamesArray, SetPassive, NonPlayableCharacter::SetPosition, SetRandomMessage.
void GenericFriendly::PrintMessage(MapManager &m)
References Macro::GoToScreenPosition, MapManager::height, message.
Referenced by Player::EnterMessageMode.
string GenericFriendly::GetMessage()
References message.
void GenericFriendly::SetNamesArray() override
References NonPlayableCharacter::name_array.
Referenced by GenericFriendly.
void GenericFriendly::SetPassive() override
References NonPlayableCharacter::passive.
Referenced by GenericFriendly.
void GenericFriendly::SetMessages()
References messages_array.
Referenced by GenericFriendly.
void GenericFriendly::SetRandomMessage()
References Macro::GenerateRandomNumber, message, messages_array.
Referenced by GenericFriendly.