ConsoleWindowManager
COLORS
HANDLE ConsoleWindowManager::HANDLE_CONSOLE
Referenced by GetConsoleHandle.
HWND ConsoleWindowManager::HANDLE_WINDOW_DESKTOP
Referenced by GetDesktopHandleWindow.
HWND ConsoleWindowManager::HANDLE_WINDOW_CONSOLE
Referenced by GetConsoleHandleWindow.
void ConsoleWindowManager::BlankScreen()
Referenced by InventoryManager::DropItemSelected, MapManager::LoadNextMap, ConsoleRendering::Render_Inventory, MapManager::RenderMap, InventoryManager::UsePotionSelected.
void ConsoleWindowManager::HideConsoleCursor()
References GetConsoleHandle.
Referenced by main.
void ConsoleWindowManager::SetWindowDisplay(int width, int height)
References GetConsoleHandleWindow.
Referenced by main.
void ConsoleWindowManager::SetText()
References GetConsoleHandle.
Referenced by main.
void ConsoleWindowManager::SetConsoleWindowColor(COLORS fg, COLORS bg)
References GetConsoleHandle.
Referenced by MapManager::PrintMap, Player::RenderPlayer.
void ConsoleWindowManager::SetConsoleWindowRandomColor(int random_color)
References BLACK, GetConsoleHandle.
Referenced by TitleScreenManager::PrintTitle.
void ConsoleWindowManager::RepositionWindow(int width, int height)
HANDLE ConsoleWindowManager::GetConsoleHandle()
References HANDLE_CONSOLE.
Referenced by HideConsoleCursor, SetConsoleWindowColor, SetConsoleWindowRandomColor, SetText.
HWND ConsoleWindowManager::GetDesktopHandleWindow()
References HANDLE_WINDOW_DESKTOP.
HWND ConsoleWindowManager::GetConsoleHandleWindow()
References HANDLE_WINDOW_CONSOLE.
Referenced by SetWindowDisplay.