ConsoleRendering
void ConsoleRendering::Render_All(ConsoleWindowManager &c, MapManager &m, Player &p, InventoryManager &i, UserInterfaceManager &ui)
References Player::in_combat, Render_Actions, Render_GUI, Render_Stats.
Referenced by main.
void ConsoleRendering::Render_GUI(MapManager &m, InventoryManager &i)
References Macro::GoToScreenPosition, MapManager::height, InventoryManager::inventory_open.
Referenced by Render_All.
void ConsoleRendering::Render_Stats(MapManager &m, Player &p, InventoryManager &i, UserInterfaceManager &ui)
References Print_Stats.
Referenced by Render_All.
void ConsoleRendering::Render_Inventory(ConsoleWindowManager &c, MapManager &m, InventoryManager &i, UserInterfaceManager &ui)
References ConsoleWindowManager::BlankScreen, InventoryManager::inventory_open, Print_Inventory, MapManager::RenderMap.
Referenced by InventoryManager::DropItemSelected, InventoryManager::InventoryControl, InventoryManager::InventoryInput, InventoryManager::UsePotionSelected.
void ConsoleRendering::Render_Actions(MapManager &m, InventoryManager &i, UserInterfaceManager &ui)
References Print_Actions_GUI.
Referenced by Render_All.
void ConsoleRendering::Print_Actions_GUI(MapManager &m, InventoryManager &i, UserInterfaceManager &ui)
References UserInterfaceManager::actions, Macro::GoToScreenPosition, MapManager::height, Macro::ReplaceAll.
Referenced by Render_Actions.
void ConsoleRendering::Print_Stats(MapManager &m, Player &p, InventoryManager &i, UserInterfaceManager &ui)
References Macro::GoToScreenPosition, Player::health, MapManager::height, Player::magic, Macro::ReplaceAll, Player::shield, UserInterfaceManager::stats.
Referenced by Render_Stats.
void ConsoleRendering::Print_Inventory(InventoryManager &i, UserInterfaceManager &ui)
References UserInterfaceManager::inventory, Macro::ReplaceAll.
Referenced by Render_Inventory.
void ConsoleRendering::Print_Actions(char action, MapManager &m)
References Macro::GoToScreenPosition, MapManager::height.
void ConsoleRendering::Create_Stats_GUI(std::string &inventory)
void ConsoleRendering::Create_Inventory_GUI(std::string &inventory)