TitleScreenManager
bool TitleScreenManager::on_title_screen
Referenced by WaitForInput.
char* TitleScreenManager::title_map
Referenced by LoadTitle, PrintTitle, ReadTitle.
string TitleScreenManager::title_screen_file_contents
Referenced by ReadTitle, RenderTitle.
const int TitleScreenManager::screen_width
Referenced by RenderTitle.
const int TitleScreenManager::screen_height
Referenced by RenderTitle.
int TitleScreenManager::width
Referenced by LoadTitle, PrintTitle, ReadTitle, RenderTitle.
int TitleScreenManager::height
Referenced by LoadTitle, PrintTitle, ReadTitle, RenderTitle, WaitForInput.
void TitleScreenManager::WaitForInput()
References Macro::GoToScreenPosition, height, on_title_screen.
Referenced by RenderTitle.
void TitleScreenManager::LoadTitle(int width, int height, string input)
References height, title_map, width.
Referenced by RenderTitle.
void TitleScreenManager::ReadTitle()
References height, title_map, title_screen_file_contents, width.
Referenced by RenderTitle.
void TitleScreenManager::PrintTitle(int width, int height, ConsoleWindowManager &cw_manager)
References height, ConsoleWindowManager::SetConsoleWindowRandomColor, title_map, width.
Referenced by RenderTitle.
void TitleScreenManager::RenderTitle(ConsoleWindowManager &cw_manager)
References height, LoadTitle, PrintTitle, ReadTitle, Macro::RepositionWindow, screen_height, screen_width, title_screen_file_contents, WaitForInput, width.
Referenced by main.