MapManager
unsigned int MapManager::level_index
Referenced by LoadNextMap, ReadMap.
unsigned int MapManager::width
Referenced by Player::BlankPosition, InventoryManager::DropItemSelected, FindEnemy, FindFriendly, IsEmpty, LoadMap, Player::PlayerCollisions, PrintMap, ReadMap, Player::RenderPlayer.
unsigned int MapManager::height
Referenced by Debug::DebugControls, Player::EnterCombatMode, Player::EnterMessageMode, LoadMap, LoadNextMap, ConsoleRendering::Print_Actions, ConsoleRendering::Print_Actions_GUI, ConsoleRendering::Print_Stats, Enemy::PrintDetails, PrintMap, GenericFriendly::PrintMessage, CombatManager::PrintStatements, ReadMap, ConsoleRendering::Render_GUI.
vector<GenericFriendly> MapManager::generic_friendlies
Referenced by FindFriendly, Player::PlayerCollisions, PrintMap.
vector<Enemy> MapManager::enemies
Referenced by FindEnemy, Player::PlayerCollisions, Player::PlayerInput, PrintMap.
char* MapManager::new_map
Referenced by Player::BlankPosition, InventoryManager::DropItemSelected, IsEmpty, LoadMap, Player::PlayerCollisions, PrintMap, ReadMap, Player::RenderPlayer.
bool MapManager::has_rendered_map
Referenced by LoadNextMap, RenderMap.
bool MapManager::loading_next_map
Referenced by LoadNextMap, main.
string MapManager::file_name_start
Referenced by ReadMap.
string MapManager::file_name_end
Referenced by ReadMap.
string MapManager::file_contents_read_in
Referenced by Player::PlayerCollisions, ReadMap, RenderMap.
void MapManager::LoadNextMap(MapManager &m, ConsoleWindowManager &c, Player &p, InventoryManager &i)
References ConsoleWindowManager::BlankScreen, Macro::GoToScreenPosition, has_rendered_map, height, Player::in_combat, level_index, loading_next_map, Player::player_position_x_new, Player::player_position_y_new, RenderMap, Player::RenderPlayer.
Referenced by Player::PlayerCollisions.
void MapManager::RenderMap(ConsoleWindowManager &c)
References ConsoleWindowManager::BlankScreen, file_contents_read_in, has_rendered_map, LoadMap, PrintMap, ReadMap.
Referenced by LoadNextMap, main, ConsoleRendering::Render_Inventory.
bool MapManager::IsEmpty(int x, int y)
References new_map, width.
Referenced by InventoryManager::DropItemSelected.
void MapManager::LoadMap(string input)
References height, new_map, width.
Referenced by RenderMap.
int MapManager::FindEnemy(Player &p)
References enemies, Player::player_position_x_new, Player::player_position_y_new, width.
Referenced by Player::PlayerCollisions, Player::PlayerInput.
int MapManager::FindFriendly(Player &p)
References generic_friendlies, Player::player_position_x_new, Player::player_position_y_new, width.
Referenced by Player::PlayerCollisions.
void MapManager::ReadMap()
References file_contents_read_in, file_name_end, file_name_start, height, level_index, new_map, width.
Referenced by RenderMap.
void MapManager::PrintMap(ConsoleWindowManager &c)
References ConsoleWindowManager::BLACK, ConsoleWindowManager::BLUE, ConsoleWindowManager::CYAN, ConsoleWindowManager::DARK_BLUE, enemies, generic_friendlies, ConsoleWindowManager::GREEN, height, ConsoleWindowManager::LIGHT_BLUE, ConsoleWindowManager::MAGENTA, new_map, ConsoleWindowManager::RED, ConsoleWindowManager::SetConsoleWindowColor, width, ConsoleWindowManager::YELLOW.
Referenced by RefreshMap, RenderMap.
void MapManager::RefreshMap(ConsoleWindowManager &c)
References Macro::GoToScreenPosition, PrintMap.