Potion
POTION_TYPE
string Potion::POTION_NAME_CHOICES[3][6][3][6]
Referenced by SetPotionName.
string Potion::name
Referenced by CreateNewPotion, SetPotionName, SetStrength.
int Potion::strength
Referenced by CreateNewPotion.
int Potion::weight
Referenced by CreateNewPotion.
POTION_TYPE Potion::POTION_TYPE_SELECTED
Referenced by CreateNewPotion, SetPotionName.
const char Potion::SYMBOL
Potion::Potion()
References CreateNewPotion.
Potion::~Potion()
unsigned int Potion::GenerateRandomNumber(int max)
Referenced by CreateNewPotion.
Potion::POTION_TYPE Potion::SetPotionType(int potion_choice)
Referenced by CreateNewPotion.
string Potion::SetPotionName(int potion_name_index, POTION_TYPE POTION_TYPE_SELECTED)
References name, POTION_NAME_CHOICES, POTION_TYPE_SELECTED.
Referenced by CreateNewPotion.
int Potion::SetStrength(string name)
References name.
Referenced by CreateNewPotion.
void Potion::CreateNewPotion()
References GenerateRandomNumber, name, POTION_TYPE_SELECTED, SetPotionName, SetPotionType, SetStrength, strength, weight.
Referenced by Potion.