RandomItemGenerator
string RandomItemGenerator::name
Referenced by RandomItemGenerator.
string RandomItemGenerator::type
Referenced by CreateItem, RandomItemGenerator, RandomWeapon::SetType.
string RandomItemGenerator::ITEM_TYPES[20][20]
Referenced by CreateItem, RandomWeapon::SetItemNames.
int RandomItemGenerator::strength
Referenced by RandomItemGenerator, SetStrength.
int RandomItemGenerator::weight
Referenced by RandomItemGenerator, SetWeight.
int RandomItemGenerator::speed
Referenced by RandomItemGenerator, SetSpeed.
char RandomItemGenerator::symbol
Referenced by CreateItem, RandomItemGenerator, SetSymbol.
RandomItemGenerator::RandomItemGenerator()
References name, speed, strength, symbol, type, weight.
RandomItemGenerator::~RandomItemGenerator()
void RandomItemGenerator::SetType(int choice)
Referenced by CreateItem.
void RandomItemGenerator::SetItemNames(string file_name)
void RandomItemGenerator::SetName(int name_index, string type)
Referenced by CreateItem.
void RandomItemGenerator::SetStrength()
References Macro::GenerateRandomNumber, strength.
Referenced by CreateItem.
void RandomItemGenerator::SetWeight()
References Macro::GenerateRandomNumber, weight.
Referenced by CreateItem.
void RandomItemGenerator::SetSpeed()
References Macro::GenerateRandomNumber, speed.
Referenced by CreateItem.
void RandomItemGenerator::SetSymbol(char symbol)
References symbol.
Referenced by CreateItem.
void RandomItemGenerator::CreateItem(char symbol, char item_type_amount)
References Macro::GenerateRandomNumber, ITEM_TYPES, SetName, SetSpeed, SetStrength, SetSymbol, SetType, SetWeight, symbol, type.
Referenced by RandomWeapon::GenerateRandomWeapon.