NonPlayableCharacter
NPC_TYPE
bool NonPlayableCharacter::passive
Referenced by CreateNonPlayableCharacter, NonPlayableCharacter, Enemy::SetPassive, GenericFriendly::SetPassive, SetSymbol.
string NonPlayableCharacter::name
Referenced by GetName, NonPlayableCharacter, Enemy::PrintDetails, SetName.
string NonPlayableCharacter::name_array[20][20]
Referenced by SetName, Enemy::SetNamesArray, GenericFriendly::SetNamesArray.
unsigned int NonPlayableCharacter::strength
Referenced by GetDamage, NonPlayableCharacter, SetStrength.
char NonPlayableCharacter::symbol
Referenced by NonPlayableCharacter, SetSymbol.
unsigned int NonPlayableCharacter::health
Referenced by GetHealth, NonPlayableCharacter, Enemy::PrintDetails, SetDesiredHealth, SetHealth.
unsigned int NonPlayableCharacter::attack_speed
Referenced by NonPlayableCharacter, SetSpeed.
unsigned int NonPlayableCharacter::npc_x
Referenced by GetX, NonPlayableCharacter, SetPosition.
unsigned int NonPlayableCharacter::npc_y
Referenced by GetY, NonPlayableCharacter, SetPosition.
NonPlayableCharacter::NonPlayableCharacter()
References attack_speed, health, name, npc_x, npc_y, passive, strength, symbol.
NonPlayableCharacter::~NonPlayableCharacter()=default
void NonPlayableCharacter::SetNamesArray()
Referenced by CreateNonPlayableCharacter.
void NonPlayableCharacter::SetPassive()
Referenced by CreateNonPlayableCharacter.
void NonPlayableCharacter::SetName()
References Macro::GenerateRandomNumber, name, name_array.
Referenced by CreateNonPlayableCharacter, Enemy::Enemy.
void NonPlayableCharacter::SetStrength()
References Macro::GenerateRandomNumberWithoutZero, strength.
Referenced by CreateNonPlayableCharacter, Enemy::Enemy.
void NonPlayableCharacter::SetHealth()
References Macro::GenerateRandomNumberWithoutZero, health.
Referenced by CreateNonPlayableCharacter, Enemy::Enemy.
void NonPlayableCharacter::SetSpeed()
References attack_speed, Macro::GenerateRandomNumberWithoutZero.
Referenced by CreateNonPlayableCharacter, Enemy::Enemy.
void NonPlayableCharacter::SetSymbol()
References ENEMY, GENERIC_FRIENDLY, passive, symbol.
Referenced by CreateNonPlayableCharacter.
void NonPlayableCharacter::SetPosition(int x, int y)
References npc_x, npc_y.
Referenced by Enemy::Enemy, GenericFriendly::GenericFriendly.
void NonPlayableCharacter::SetDesiredHealth(int value)
References health.
Referenced by CombatManager::HitEnemy.
string NonPlayableCharacter::GetName()
References name.
Referenced by Enemy::PrintDetails, CombatManager::PrintStatements.
int NonPlayableCharacter::GetHealth()
References health.
Referenced by CombatManager::HitEnemy, Enemy::PrintDetails, CombatManager::PrintStatements, CombatManager::UpdateResults.
int NonPlayableCharacter::GetDamage()
References strength.
Referenced by CombatManager::HitPlayer, Enemy::PrintDetails, CombatManager::PrintStatements.
int NonPlayableCharacter::GetX()
References npc_x.
int NonPlayableCharacter::GetY()
References npc_y.
void NonPlayableCharacter::CreateNonPlayableCharacter()
References passive, SetHealth, SetName, SetNamesArray, SetPassive, SetSpeed, SetStrength, SetSymbol.