Macro
void Macro::GoToScreenPosition(short C, short R)
Referenced by Debug::DebugControls, Player::EnterCombatMode, Player::EnterMessageMode, MapManager::LoadNextMap, ConsoleRendering::Print_Actions, ConsoleRendering::Print_Actions_GUI, ConsoleRendering::Print_Stats, Enemy::PrintDetails, GenericFriendly::PrintMessage, CombatManager::PrintStatements, MapManager::RefreshMap, ConsoleRendering::Render_GUI, Player::RenderPlayer, TitleScreenManager::WaitForInput.
void Macro::RepositionWindow(int width, int height)
Referenced by TitleScreenManager::RenderTitle.
string Macro::ReplaceAll(string str, const string &from, const string &to)
Referenced by ConsoleRendering::Print_Actions_GUI, ConsoleRendering::Print_Inventory, ConsoleRendering::Print_Stats.
int Macro::Separate(int input, char from, char count)
int Macro::GenerateRandomNumber(int max)
Referenced by RandomItemGenerator::CreateItem, NonPlayableCharacter::SetName, GenericFriendly::SetRandomMessage, RandomItemGenerator::SetSpeed, RandomItemGenerator::SetStrength, RandomWeapon::SetType, RandomItemGenerator::SetWeight.
int Macro::GenerateRandomNumberWithoutZero(int max)
Referenced by NonPlayableCharacter::SetHealth, NonPlayableCharacter::SetSpeed, NonPlayableCharacter::SetStrength.