.TH "D:/University/ca-A00269349/Rogue Directory Reference" 3 "Wed Nov 17 2021" "Version 1.0" "Rogue" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/University/ca-A00269349/Rogue Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArmour\&.h\fP"
.br
.ti -1c
.RI "file \fBCombatManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCombatManager\&.h\fP"
.br
.ti -1c
.RI "file \fBConsoleRendering\&.cpp\fP"
.br
.ti -1c
.RI "file \fBConsoleRendering\&.h\fP"
.br
.ti -1c
.RI "file \fBConsoleWindowManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBConsoleWindowManager\&.h\fP"
.br
.ti -1c
.RI "file \fBDebug\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDebug\&.h\fP"
.br
.ti -1c
.RI "file \fBEnemy\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEnemy\&.h\fP"
.br
.ti -1c
.RI "file \fBGenericFriendly\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGenericFriendly\&.h\fP"
.br
.ti -1c
.RI "file \fBInventoryManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBInventoryManager\&.h\fP"
.br
.ti -1c
.RI "file \fBMacro\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMacro\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMapManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMapManager\&.h\fP"
.br
.ti -1c
.RI "file \fBNonPlayableCharacter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNonPlayableCharacter\&.h\fP"
.br
.ti -1c
.RI "file \fBPlayer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPlayer\&.h\fP"
.br
.ti -1c
.RI "file \fBPotion\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPotion\&.h\fP"
.br
.ti -1c
.RI "file \fBRandomItemGenerator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRandomItemGenerator\&.h\fP"
.br
.ti -1c
.RI "file \fBRandomWeapon\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRandomWeapon\&.h\fP"
.br
.ti -1c
.RI "file \fBRandomWeaponGenerator\&.h\fP"
.br
.ti -1c
.RI "file \fBTitleScreenManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTitleScreenManager\&.h\fP"
.br
.ti -1c
.RI "file \fBUserInterfaceManger\&.h\fP"
.br
.in -1c
