.TH "D:/University/ca-A00269349/Rogue/Macro.cpp" 3 "Wed Nov 17 2021" "Version 1.0" "Rogue" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/University/ca-A00269349/Rogue/Macro.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Macro\&.h'\fP
.br
\fC#include 'ConsoleWindowManager\&.h'\fP
.br
\fC#include <time\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Rogue from the source code\&.
