.TH "D:/University/ca-A00269349/Rogue/Macro.h" 3 "Wed Nov 17 2021" "Version 1.0" "Rogue" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/University/ca-A00269349/Rogue/Macro.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMacro\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBMacro::GoToScreenPosition\fP (short C, short R)"
.br
.ti -1c
.RI "void \fBMacro::RepositionWindow\fP (int width, int height)"
.br
.ti -1c
.RI "string \fBMacro::ReplaceAll\fP (string str, const string &from, const string &to)"
.br
.ti -1c
.RI "int \fBMacro::Separate\fP (int input, char from, char count)"
.br
.ti -1c
.RI "int \fBMacro::GenerateRandomNumber\fP (int max)"
.br
.ti -1c
.RI "int \fBMacro::GenerateRandomNumberWithoutZero\fP (int max)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rogue from the source code\&.
