.TH "D:/University/ca-A00269349/Rogue/Player.h" 3 "Wed Nov 17 2021" "Version 1.0" "Rogue" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/University/ca-A00269349/Rogue/Player.h
.SH SYNOPSIS
.br
.PP
\fC#include 'InventoryManager\&.h'\fP
.br
\fC#include 'ConsoleWindowManager\&.h'\fP
.br
\fC#include 'UserInterfaceManger\&.h'\fP
.br
\fC#include 'Enemy\&.h'\fP
.br
\fC#include 'GenericFriendly\&.h'\fP
.br
\fC#include 'CombatManager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Rogue from the source code\&.
