.TH "D:/University/ca-A00269349/Rogue/Rogue.cpp" 3 "Mon Nov 1 2021" "Version 1.0" "Rogue" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/University/ca-A00269349/Rogue/Rogue.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ConsoleRendering\&.h'\fP
.br
\fC#include 'Player\&.h'\fP
.br
\fC#include 'MapManager\&.h'\fP
.br
\fC#include 'ConsoleWindowManager\&.h'\fP
.br
\fC#include 'InventoryManager\&.h'\fP
.br
\fC#include 'Macro\&.h'\fP
.br
\fC#include 'TitleScreenManager\&.h'\fP
.br
\fC#include 'UserInterfaceManger\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBUserInterfaceManager\fP \fBUSER_INTERFACE_MANGER\fP"
.br
.ti -1c
.RI "\fBConsoleWindowManager\fP \fBCONSOLE_WINDOW_CONTROL\fP"
.br
.ti -1c
.RI "\fBConsoleRendering\fP \fBCONSOLE_RENDERING\fP"
.br
.ti -1c
.RI "\fBTitleScreenManager\fP \fBTITLE_SCREEN_MANAGER\fP"
.br
.ti -1c
.RI "\fBInventoryManager\fP \fBINVENTORY_MANAGER\fP"
.br
.ti -1c
.RI "\fBMapManager\fP \fBMAP_MANAGER\fP"
.br
.ti -1c
.RI "\fBPlayer\fP \fBPLAYER\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void main ()"

.PP
Definition at line \fB21\fP of file \fBRogue\&.cpp\fP\&.
.PP
.nf
22 {
23     CONSOLE_WINDOW_CONTROL\&.SetText();
24     CONSOLE_WINDOW_CONTROL\&.ShowConsoleCursor(false);
25     TITLE_SCREEN_MANAGER\&.RenderTitle(CONSOLE_WINDOW_CONTROL);
26     CONSOLE_WINDOW_CONTROL\&.SetWindowDisplay(850, 550);
27 
28     MAP_MANAGER\&.RenderMap(CONSOLE_WINDOW_CONTROL);
29     while (true)
30     {
31         while (!MAP_MANAGER\&.loading_next_map)
32         {
33             CONSOLE_WINDOW_CONTROL\&.ShowConsoleCursor(false);
34             INVENTORY_MANAGER\&.CurrentInventoryIndex(INVENTORY_MANAGER);
35             INVENTORY_MANAGER\&.UpdateInventory(INVENTORY_MANAGER, USER_INTERFACE_MANGER);
36             PLAYER\&.PlayerInput(INVENTORY_MANAGER, CONSOLE_WINDOW_CONTROL, MAP_MANAGER, PLAYER, CONSOLE_RENDERING, USER_INTERFACE_MANGER);
37             INVENTORY_MANAGER\&.InventoryInput(CONSOLE_WINDOW_CONTROL, MAP_MANAGER, INVENTORY_MANAGER, CONSOLE_RENDERING, USER_INTERFACE_MANGER);
38             PLAYER\&.PlayerCollisions(MAP_MANAGER, CONSOLE_WINDOW_CONTROL, PLAYER, INVENTORY_MANAGER, USER_INTERFACE_MANGER);
39             PLAYER\&.RenderPlayer(MAP_MANAGER, CONSOLE_WINDOW_CONTROL, INVENTORY_MANAGER);
40             CONSOLE_RENDERING\&.Render_All(CONSOLE_WINDOW_CONTROL, MAP_MANAGER, PLAYER, INVENTORY_MANAGER, USER_INTERFACE_MANGER);
41         }
42     }
43 }
.fi
.SH "Variable Documentation"
.PP 
.SS "\fBConsoleRendering\fP CONSOLE_RENDERING"

.PP
Definition at line \fB15\fP of file \fBRogue\&.cpp\fP\&.
.SS "\fBConsoleWindowManager\fP CONSOLE_WINDOW_CONTROL"

.PP
Definition at line \fB14\fP of file \fBRogue\&.cpp\fP\&.
.SS "\fBInventoryManager\fP INVENTORY_MANAGER"

.PP
Definition at line \fB17\fP of file \fBRogue\&.cpp\fP\&.
.SS "\fBMapManager\fP MAP_MANAGER"

.PP
Definition at line \fB18\fP of file \fBRogue\&.cpp\fP\&.
.SS "\fBPlayer\fP PLAYER"

.PP
Definition at line \fB19\fP of file \fBRogue\&.cpp\fP\&.
.SS "\fBTitleScreenManager\fP TITLE_SCREEN_MANAGER"

.PP
Definition at line \fB16\fP of file \fBRogue\&.cpp\fP\&.
.SS "\fBUserInterfaceManager\fP USER_INTERFACE_MANGER"

.PP
Definition at line \fB13\fP of file \fBRogue\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Rogue from the source code\&.
