.TH "D:/University/ca-A00269349/Rogue/StatsManager.cpp" 3 "Mon Nov 1 2021" "Version 1.0" "Rogue" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/University/ca-A00269349/Rogue/StatsManager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'StatsManager\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Rogue from the source code\&.
