.TH "StatsManager" 3 "Mon Nov 1 2021" "Version 1.0" "Rogue" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatsManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StatsManager\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBStatsManager\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rogue from the source code\&.
