.TH "D:/University/ca-A00269349/Rogue/TitleScreenManager.cpp" 3 "Wed Nov 17 2021" "Version 1.0" "Rogue" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/University/ca-A00269349/Rogue/TitleScreenManager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'TitleScreenManager\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'ConsoleWindowManager\&.h'\fP
.br
\fC#include 'Macro\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <windows\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <regex>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Rogue from the source code\&.
