.TH "UserInterfaceManager" 3 "Wed Nov 17 2021" "Version 1.0" "Rogue" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserInterfaceManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UserInterfaceManger\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBactions\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBstats\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBinventory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBUserInterfaceManger\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::string> UserInterfaceManager::actions"
\fBInitial value:\fP
.PP
.nf
{
        "<------------------------------------------- A C T I O N S ->",
        "|                                                           |",
        "|                                                           |",
        "|                                                           |",
        "|                                                           |",
        "|                                                           |",
        "|                                                           |",
        "|                                                           |",
        ":-----------------------------------------------------------;",
    }
.fi
.PP
Definition at line \fB8\fP of file \fBUserInterfaceManger\&.h\fP\&.
.SS "std::vector<std::string> UserInterfaceManager::inventory"
\fBInitial value:\fP
.PP
.nf
{
        "<------------------------------------------------------------------------------- I N V E N T O R Y ->",
        "/-- P O T I O N S ----------------------------------------------------------------------------------]",
        "| HEALTH 0                                                                                          |",
        "| SHIELD 0                                                                                          |",
        "| MAGIC 0                                                                                           |",
        "/-- W E A P O N S ----------------------------------------------------------------------------------]",
        "| BLADE OF A THOUSAND CUTS                                                                          |",
        "| NIGHTBANE                                                                                         |",
        "| VENOM CARVER                                                                                      |",
        "| ANNIHILATION SABRE                                                                                |",
        "/-- A R M O U R ------------------------------------------------------------------------------------]",
        "| SOLDIER'S TUNIC OF CATACLYSMS                                                                     |",
        "| SILENT ARMOR OF THE WICKED                                                                        |",
        "| STORMGUARD DEMON GREATPLATE                                                                       |",
        "/-- T R I N K E T S --------------------------------------------------------------------------------]",
        "| MIGHT OF FALLEN SOULS                                                                             |",
        "| HOPE OF CARNAGE                                                                                   |",
        "/---------------------------------------------------------------------------------------------------]",
        "|                                                                                                   |",
        ":---------------------------------------------------------------------------------------------------;"
    }
.fi
.PP
Definition at line \fB32\fP of file \fBUserInterfaceManger\&.h\fP\&.
.SS "std::vector<std::string> UserInterfaceManager::stats"
\fBInitial value:\fP
.PP
.nf
{
        "<-------------------v---- S T A T S ->",
        "|                   |                |",
        "|   H E A L T H     |                |",
        "|                   |                |",
        "|   S H I E L D     |                |",
        "|                   |                |",
        "|   M A G I C       |                |",
        "|                   |                |",
        ":-------------------^----------------;",
    }
.fi
.PP
Definition at line \fB20\fP of file \fBUserInterfaceManger\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Rogue from the source code\&.
